### PR TITLE
Update RobotContainer.java

### PR DESCRIPTION
**Pull request by arnavb-02**
Changed operator stick controls for Girls Gen 2024.

### CODE REVIEW

**Comment by cole-wilson** [comment]
This looks good 👍

**Comment by arnavb-02** [comment]
Thank you for confirming Cole!

**Comment by Vikaat** [comment]
@cole-wilson I don't have merge access, can you merge Arnav's changes?

**Comment by cole-wilson** [comment]
See external conversation, move to girls-gen branch.

**Pull request closed without merging**
